package com.vaushell.treetasker.application.login;

import com.vaadin.annotations.AutoGenerated;
import com.vaadin.ui.Alignment;
import com.vaadin.ui.Button;
import com.vaadin.ui.Button.ClickEvent;
import com.vaadin.ui.CustomComponent;
import com.vaadin.ui.GridLayout;
import com.vaadin.ui.Label;
import com.vaadin.ui.Panel;
import com.vaadin.ui.PasswordField;
import com.vaadin.ui.TextField;
import com.vaadin.ui.VerticalLayout;
import com.vaadin.ui.Window.Notification;
import com.vaadin.ui.themes.BaseTheme;
import com.vaushell.treetasker.application.TreeTaskerWebApplicationController;

public class TTWLoginLayout
	extends CustomComponent
{

	/**
	 * 
	 */
	private static final long	serialVersionUID	= 1L;

	/**
	 * The constructor should first build the main layout, set the composition
	 * root and then do any custom initialization.
	 * 
	 * The constructor will not be automatically regenerated by the visual
	 * editor.
	 */
	public TTWLoginLayout(
		TreeTaskerWebApplicationController controller )
	{
		this.controller = controller;
		buildMainLayout();
		setCompositionRoot( mainLayout );

		initComponents();
	}

	@AutoGenerated
	private VerticalLayout buildMainLayout() {
		// common part: create layout
		mainLayout = new VerticalLayout();
		mainLayout.setImmediate( false );
		mainLayout.setWidth( "100%" );
		mainLayout.setHeight( "100%" );
		mainLayout.setMargin( true );

		// top-level component properties
		setWidth( "100.0%" );
		setHeight( "100.0%" );

		// vPBLloginForm
		vPBLloginForm = buildVPBLloginForm();
		mainLayout.addComponent( vPBLloginForm );
		mainLayout.setExpandRatio( vPBLloginForm, 1.0f );
		mainLayout.setComponentAlignment( vPBLloginForm, new Alignment( 20 ) );

		return mainLayout;
	}

	@AutoGenerated
	private GridLayout buildVFormLayout() {
		// common part: create layout
		vFormLayout = new GridLayout();
		vFormLayout.setImmediate( false );
		vFormLayout.setWidth( "100.0%" );
		vFormLayout.setHeight( "100.0%" );
		vFormLayout.setMargin( true );
		vFormLayout.setSpacing( true );
		vFormLayout.setColumns( 2 );
		vFormLayout.setRows( 4 );

		// vLBLuserName
		vLBLuserName = new Label();
		vLBLuserName.setImmediate( false );
		vLBLuserName.setWidth( "-1px" );
		vLBLuserName.setHeight( "-1px" );
		vLBLuserName.setValue( "E-mail :" );
		vFormLayout.addComponent( vLBLuserName, 0, 0 );
		vFormLayout.setComponentAlignment( vLBLuserName, new Alignment( 33 ) );

		// vTFuserNameValue
		vTFuserNameValue = new TextField();
		vTFuserNameValue.setImmediate( true );
		vTFuserNameValue.setWidth( "-1px" );
		vTFuserNameValue.setHeight( "-1px" );
		vTFuserNameValue.setInputPrompt( "E-mail" );
		vFormLayout.addComponent( vTFuserNameValue, 1, 0 );
		vFormLayout.setComponentAlignment( vTFuserNameValue, new Alignment( 33 ) );

		// vLBLpassword
		vLBLpassword = new Label();
		vLBLpassword.setImmediate( false );
		vLBLpassword.setWidth( "-1px" );
		vLBLpassword.setHeight( "-1px" );
		vLBLpassword.setValue( "Mot de passe :" );
		vFormLayout.addComponent( vLBLpassword, 0, 1 );

		// vTFpasswordValue
		vTFpasswordValue = new PasswordField();
		vTFpasswordValue.setImmediate( true );
		vTFpasswordValue.setWidth( "-1px" );
		vTFpasswordValue.setHeight( "-1px" );
		vTFpasswordValue.setInputPrompt( "password" );
		vFormLayout.addComponent( vTFpasswordValue, 1, 1 );
		vFormLayout.setComponentAlignment( vTFpasswordValue, new Alignment( 33 ) );

		// vBTregister
		vBTregister = new Button();
		vBTregister.setCaption( "S'enregistrer" );
		vBTregister.setImmediate( true );
		vBTregister.setWidth( "-1px" );
		vBTregister.setHeight( "26px" );
		vFormLayout.addComponent( vBTregister, 1, 2 );
		vFormLayout.setComponentAlignment( vBTregister, new Alignment( 33 ) );

		// vBTlogin
		vBTlogin = new Button();
		vBTlogin.setCaption( "Se connecter" );
		vBTlogin.setImmediate( true );
		vBTlogin.setWidth( "-1px" );
		vBTlogin.setHeight( "-1px" );
		vFormLayout.addComponent( vBTlogin, 1, 3 );

		return vFormLayout;
	}

	@AutoGenerated
	private Panel buildVPBLloginForm() {
		// common part: create layout
		vPBLloginForm = new Panel();
		vPBLloginForm.setCaption( "Connexion TreeTasker" );
		vPBLloginForm.setImmediate( false );
		vPBLloginForm.setWidth( "500px" );
		vPBLloginForm.setHeight( "-1px" );

		// vFormLayout
		vFormLayout = buildVFormLayout();
		vPBLloginForm.setContent( vFormLayout );

		return vPBLloginForm;
	}

	private void initComponents() {
		// initListeners
		// Login
		vBTlogin.addListener( new Button.ClickListener()
		{

			/**
			 * 
			 */
			private static final long	serialVersionUID	= 1L;

			@Override
			public void buttonClick(
				ClickEvent event ) {
				if ( controller.login( (String) vTFuserNameValue.getValue(), (String) vTFpasswordValue.getValue() ) )
				{
					controller.showUserWindow();
				}
				else
				{
					controller.getUserWindow().showNotification( "E-mail ou mot de passe incorrect", "",
						Notification.TYPE_ERROR_MESSAGE );
				}

			}
		} );
		// Register
		vBTregister.setStyleName( BaseTheme.BUTTON_LINK );
		vBTregister.addListener( new Button.ClickListener()
		{

			private static final long	serialVersionUID	= 1L;

			@Override
			public void buttonClick(
				ClickEvent event ) {
				controller.queryRegistration();
			}
		} );

		vBTregister.setStyleName( BaseTheme.BUTTON_LINK );
		vFormLayout.setColumnExpandRatio( 1, 1 );
	}

	private final TreeTaskerWebApplicationController	controller;

	@AutoGenerated
	private VerticalLayout								mainLayout;
	@AutoGenerated
	private Panel										vPBLloginForm;
	@AutoGenerated
	private GridLayout									vFormLayout;
	@AutoGenerated
	private Button										vBTlogin;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private Button										vBTregister;

	@AutoGenerated
	private PasswordField								vTFpasswordValue;

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	/*- VaadinEditorProperties={"grid":"RegularGrid,20","showGrid":true,"snapToGrid":true,"snapToObject":true,"movingGuides":false,"snappingDistance":10} */

	@AutoGenerated
	private Label										vLBLpassword;

	@AutoGenerated
	private TextField									vTFuserNameValue;

	@AutoGenerated
	private Label										vLBLuserName;

}
